// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
)

const deleteAccount = `-- name: DeleteAccount :execrows
DELETE FROM accounts WHERE platform = ? AND role = ?
`

type DeleteAccountParams struct {
	Platform string
	Role     string
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccount, arg.Platform, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAccount = `-- name: GetAccount :one
SELECT platform, role, login, user_id, scopes, client_id, flow, updated_at FROM accounts WHERE platform = ? AND role = ?
`

type GetAccountParams struct {
	Platform string
	Role     string
}

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.Platform, arg.Role)
	var i Account
	err := row.Scan(
		&i.Platform,
		&i.Role,
		&i.Login,
		&i.UserID,
		&i.Scopes,
		&i.ClientID,
		&i.Flow,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT platform, role, login, user_id, scopes, client_id, flow, updated_at FROM accounts ORDER BY platform, role
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Platform,
			&i.Role,
			&i.Login,
			&i.UserID,
			&i.Scopes,
			&i.ClientID,
			&i.Flow,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (platform, role, login, user_id, scopes, client_id, flow, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (platform, role) DO UPDATE SET
    login = excluded.login,
    user_id = excluded.user_id,
    scopes = excluded.scopes,
    client_id = excluded.client_id,
    flow = excluded.flow,
    updated_at = excluded.updated_at
`

type UpsertAccountParams struct {
	Platform  string
	Role      string
	Login     string
	UserID    string
	Scopes    string
	ClientID  string
	Flow      string
	UpdatedAt int64
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.Platform,
		arg.Role,
		arg.Login,
		arg.UserID,
		arg.Scopes,
		arg.ClientID,
		arg.Flow,
		arg.UpdatedAt,
	)
	return err
}
