// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteCommand = `-- name: DeleteCommand :execrows
DELETE FROM commands WHERE id = ?
`

func (q *Queries) DeleteCommand(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommand, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteCommandGroup = `-- name: DeleteCommandGroup :execrows
DELETE FROM command_groups WHERE id = ?
`

func (q *Queries) DeleteCommandGroup(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCommandGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteTriggers = `-- name: DeleteTriggers :exec
DELETE FROM command_triggers WHERE command_id = ?
`

func (q *Queries) DeleteTriggers(ctx context.Context, commandID string) error {
	_, err := q.db.ExecContext(ctx, deleteTriggers, commandID)
	return err
}

const getCommand = `-- name: GetCommand :one
SELECT id, name, kind, enabled, unlocked, group_id, wildcard, event_type, requirements, actions, created_at, updated_at FROM commands WHERE id = ?
`

func (q *Queries) GetCommand(ctx context.Context, id string) (Command, error) {
	row := q.db.QueryRowContext(ctx, getCommand, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Enabled,
		&i.Unlocked,
		&i.GroupID,
		&i.Wildcard,
		&i.EventType,
		&i.Requirements,
		&i.Actions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommandGroup = `-- name: GetCommandGroup :one
SELECT id, name, name_key, timer_interval, created_at, updated_at FROM command_groups WHERE id = ?
`

func (q *Queries) GetCommandGroup(ctx context.Context, id string) (CommandGroup, error) {
	row := q.db.QueryRowContext(ctx, getCommandGroup, id)
	var i CommandGroup
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.NameKey,
		&i.TimerInterval,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTrigger = `-- name: InsertTrigger :exec
INSERT INTO command_triggers (command_id, position, trigger_text, trigger_key, active)
VALUES (?, ?, ?, ?, ?)
`

type InsertTriggerParams struct {
	CommandID   string
	Position    int64
	TriggerText string
	TriggerKey  string
	Active      int64
}

func (q *Queries) InsertTrigger(ctx context.Context, arg InsertTriggerParams) error {
	_, err := q.db.ExecContext(ctx, insertTrigger,
		arg.CommandID,
		arg.Position,
		arg.TriggerText,
		arg.TriggerKey,
		arg.Active,
	)
	return err
}

const listAllTriggers = `-- name: ListAllTriggers :many
SELECT command_id, trigger_text FROM command_triggers ORDER BY command_id, position
`

type ListAllTriggersRow struct {
	CommandID   string
	TriggerText string
}

func (q *Queries) ListAllTriggers(ctx context.Context) ([]ListAllTriggersRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllTriggersRow{}
	for rows.Next() {
		var i ListAllTriggersRow
		if err := rows.Scan(&i.CommandID, &i.TriggerText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandGroups = `-- name: ListCommandGroups :many
SELECT id, name, name_key, timer_interval, created_at, updated_at FROM command_groups ORDER BY name_key, id
`

func (q *Queries) ListCommandGroups(ctx context.Context) ([]CommandGroup, error) {
	rows, err := q.db.QueryContext(ctx, listCommandGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandGroup{}
	for rows.Next() {
		var i CommandGroup
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.NameKey,
			&i.TimerInterval,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommands = `-- name: ListCommands :many
SELECT id, name, kind, enabled, unlocked, group_id, wildcard, event_type, requirements, actions, created_at, updated_at FROM commands ORDER BY name, id
`

func (q *Queries) ListCommands(ctx context.Context) ([]Command, error) {
	rows, err := q.db.QueryContext(ctx, listCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Enabled,
			&i.Unlocked,
			&i.GroupID,
			&i.Wildcard,
			&i.EventType,
			&i.Requirements,
			&i.Actions,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggers = `-- name: ListTriggers :many
SELECT trigger_text FROM command_triggers WHERE command_id = ? ORDER BY position
`

func (q *Queries) ListTriggers(ctx context.Context, commandID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listTriggers, commandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var trigger_text string
		if err := rows.Scan(&trigger_text); err != nil {
			return nil, err
		}
		items = append(items, trigger_text)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putCommand = `-- name: PutCommand :exec
INSERT INTO commands (
    id, name, kind, enabled, unlocked, group_id, wildcard, event_type,
    requirements, actions, created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    kind = excluded.kind,
    enabled = excluded.enabled,
    unlocked = excluded.unlocked,
    group_id = excluded.group_id,
    wildcard = excluded.wildcard,
    event_type = excluded.event_type,
    requirements = excluded.requirements,
    actions = excluded.actions,
    updated_at = excluded.updated_at
`

type PutCommandParams struct {
	ID           string
	Name         string
	Kind         string
	Enabled      int64
	Unlocked     int64
	GroupID      sql.NullString
	Wildcard     int64
	EventType    sql.NullString
	Requirements string
	Actions      string
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) PutCommand(ctx context.Context, arg PutCommandParams) error {
	_, err := q.db.ExecContext(ctx, putCommand,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.Enabled,
		arg.Unlocked,
		arg.GroupID,
		arg.Wildcard,
		arg.EventType,
		arg.Requirements,
		arg.Actions,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const putCommandGroup = `-- name: PutCommandGroup :exec
INSERT INTO command_groups (id, name, name_key, timer_interval, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    name = excluded.name,
    name_key = excluded.name_key,
    timer_interval = excluded.timer_interval,
    updated_at = excluded.updated_at
`

type PutCommandGroupParams struct {
	ID            string
	Name          string
	NameKey       string
	TimerInterval int64
	CreatedAt     int64
	UpdatedAt     int64
}

func (q *Queries) PutCommandGroup(ctx context.Context, arg PutCommandGroupParams) error {
	_, err := q.db.ExecContext(ctx, putCommandGroup,
		arg.ID,
		arg.Name,
		arg.NameKey,
		arg.TimerInterval,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
