// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cooldowns.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteCooldown = `-- name: DeleteCooldown :exec
DELETE FROM cooldowns
WHERE command_id IS ?1 AND group_id IS ?2 AND user_id IS ?3
`

type DeleteCooldownParams struct {
	CommandID sql.NullString
	GroupID   sql.NullString
	UserID    sql.NullString
}

func (q *Queries) DeleteCooldown(ctx context.Context, arg DeleteCooldownParams) error {
	_, err := q.db.ExecContext(ctx, deleteCooldown, arg.CommandID, arg.GroupID, arg.UserID)
	return err
}

const deleteCooldownEndingAt = `-- name: DeleteCooldownEndingAt :exec
DELETE FROM cooldowns
WHERE command_id IS ?1 AND group_id IS ?2 AND user_id IS ?3
    AND ends_at = ?4
`

type DeleteCooldownEndingAtParams struct {
	CommandID sql.NullString
	GroupID   sql.NullString
	UserID    sql.NullString
	EndsAt    int64
}

func (q *Queries) DeleteCooldownEndingAt(ctx context.Context, arg DeleteCooldownEndingAtParams) error {
	_, err := q.db.ExecContext(ctx, deleteCooldownEndingAt,
		arg.CommandID,
		arg.GroupID,
		arg.UserID,
		arg.EndsAt,
	)
	return err
}

const deleteEndedCooldowns = `-- name: DeleteEndedCooldowns :exec
DELETE FROM cooldowns WHERE ends_at <= ?
`

func (q *Queries) DeleteEndedCooldowns(ctx context.Context, endsAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteEndedCooldowns, endsAt)
	return err
}

const getCooldownEnd = `-- name: GetCooldownEnd :one
SELECT ends_at FROM cooldowns
WHERE command_id IS ?1 AND group_id IS ?2 AND user_id IS ?3
`

type GetCooldownEndParams struct {
	CommandID sql.NullString
	GroupID   sql.NullString
	UserID    sql.NullString
}

func (q *Queries) GetCooldownEnd(ctx context.Context, arg GetCooldownEndParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCooldownEnd, arg.CommandID, arg.GroupID, arg.UserID)
	var ends_at int64
	err := row.Scan(&ends_at)
	return ends_at, err
}

const insertCooldown = `-- name: InsertCooldown :exec
INSERT INTO cooldowns (command_id, group_id, user_id, ends_at) VALUES (?, ?, ?, ?)
`

type InsertCooldownParams struct {
	CommandID sql.NullString
	GroupID   sql.NullString
	UserID    sql.NullString
	EndsAt    int64
}

func (q *Queries) InsertCooldown(ctx context.Context, arg InsertCooldownParams) error {
	_, err := q.db.ExecContext(ctx, insertCooldown,
		arg.CommandID,
		arg.GroupID,
		arg.UserID,
		arg.EndsAt,
	)
	return err
}
