// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: counters.sql

package sqlcgen

import (
	"context"
)

const deleteCounter = `-- name: DeleteCounter :execrows
DELETE FROM counters WHERE name = ?
`

func (q *Queries) DeleteCounter(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCounter, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getCounter = `-- name: GetCounter :one

SELECT id, name, value, reset_on_start, created_at, updated_at FROM counters WHERE name = ?
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetCounter(ctx context.Context, name string) (Counter, error) {
	row := q.db.QueryRowContext(ctx, getCounter, name)
	var i Counter
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.ResetOnStart,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCounter = `-- name: InsertCounter :exec
INSERT INTO counters (id, name, value, reset_on_start, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertCounterParams struct {
	ID           string
	Name         string
	Value        int64
	ResetOnStart int64
	CreatedAt    int64
	UpdatedAt    int64
}

func (q *Queries) InsertCounter(ctx context.Context, arg InsertCounterParams) error {
	_, err := q.db.ExecContext(ctx, insertCounter,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.ResetOnStart,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listCounters = `-- name: ListCounters :many
SELECT id, name, value, reset_on_start, created_at, updated_at FROM counters ORDER BY name
`

func (q *Queries) ListCounters(ctx context.Context) ([]Counter, error) {
	rows, err := q.db.QueryContext(ctx, listCounters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Counter{}
	for rows.Next() {
		var i Counter
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.ResetOnStart,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetCountersOnStart = `-- name: ResetCountersOnStart :execrows
UPDATE counters SET value = 0, updated_at = ? WHERE reset_on_start = 1
`

func (q *Queries) ResetCountersOnStart(ctx context.Context, updatedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetCountersOnStart, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateCounter = `-- name: UpdateCounter :exec
UPDATE counters SET name = ?, value = ?, reset_on_start = ?, updated_at = ? WHERE id = ?
`

type UpdateCounterParams struct {
	Name         string
	Value        int64
	ResetOnStart int64
	UpdatedAt    int64
	ID           string
}

func (q *Queries) UpdateCounter(ctx context.Context, arg UpdateCounterParams) error {
	_, err := q.db.ExecContext(ctx, updateCounter,
		arg.Name,
		arg.Value,
		arg.ResetOnStart,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
