// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteSessionEvents = `-- name: DeleteSessionEvents :exec
DELETE FROM session_events WHERE platform = ?
`

func (q *Queries) DeleteSessionEvents(ctx context.Context, platform string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionEvents, platform)
	return err
}

const insertSessionEvent = `-- name: InsertSessionEvent :execrows
INSERT INTO session_events (platform, type, user_id) VALUES (?, ?, ?) ON CONFLICT DO NOTHING
`

type InsertSessionEventParams struct {
	Platform string
	Type     string
	UserID   string
}

func (q *Queries) InsertSessionEvent(ctx context.Context, arg InsertSessionEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertSessionEvent, arg.Platform, arg.Type, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const insertUserEvent = `-- name: InsertUserEvent :execrows
INSERT INTO user_events (user_id, type) VALUES (?, ?) ON CONFLICT DO NOTHING
`

type InsertUserEventParams struct {
	UserID string
	Type   string
}

func (q *Queries) InsertUserEvent(ctx context.Context, arg InsertUserEventParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertUserEvent, arg.UserID, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listStreamSessions = `-- name: ListStreamSessions :many

SELECT platform, started_at, state, since, seen_live FROM stream_sessions ORDER BY platform
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) ListStreamSessions(ctx context.Context) ([]StreamSession, error) {
	rows, err := q.db.QueryContext(ctx, listStreamSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StreamSession{}
	for rows.Next() {
		var i StreamSession
		if err := rows.Scan(
			&i.Platform,
			&i.StartedAt,
			&i.State,
			&i.Since,
			&i.SeenLive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putStreamSession = `-- name: PutStreamSession :exec
INSERT INTO stream_sessions (platform, started_at, state, since, seen_live) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (platform) DO UPDATE SET
    started_at = excluded.started_at,
    state = excluded.state,
    since = excluded.since,
    seen_live = excluded.seen_live
`

type PutStreamSessionParams struct {
	Platform  string
	StartedAt sql.NullInt64
	State     string
	Since     sql.NullInt64
	SeenLive  sql.NullInt64
}

func (q *Queries) PutStreamSession(ctx context.Context, arg PutStreamSessionParams) error {
	_, err := q.db.ExecContext(ctx, putStreamSession,
		arg.Platform,
		arg.StartedAt,
		arg.State,
		arg.Since,
		arg.SeenLive,
	)
	return err
}
