// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Meta struct {
	Key   string
	Value string
}

type Secret struct {
	Name       string
	KeyID      string
	Nonce      []byte
	Ciphertext []byte
	UpdatedAt  int64
}

type Setting struct {
	Section   string
	Document  string
	UpdatedAt int64
}
