// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotes.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countQuotes = `-- name: CountQuotes :one
SELECT count(*) FROM quotes
`

func (q *Queries) CountQuotes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countQuotes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteQuote = `-- name: DeleteQuote :execrows
DELETE FROM quotes WHERE number = ?
`

func (q *Queries) DeleteQuote(ctx context.Context, number int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQuote, number)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getQuote = `-- name: GetQuote :one

SELECT number, id, text, game, quoted_at, added_by, created_at, updated_at FROM quotes WHERE number = ?
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetQuote(ctx context.Context, number int64) (Quote, error) {
	row := q.db.QueryRowContext(ctx, getQuote, number)
	var i Quote
	err := row.Scan(
		&i.Number,
		&i.ID,
		&i.Text,
		&i.Game,
		&i.QuotedAt,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertQuote = `-- name: InsertQuote :execlastid
INSERT INTO quotes (id, text, game, quoted_at, added_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertQuoteParams struct {
	ID        string
	Text      string
	Game      string
	QuotedAt  int64
	AddedBy   sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertQuote(ctx context.Context, arg InsertQuoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertQuote,
		arg.ID,
		arg.Text,
		arg.Game,
		arg.QuotedAt,
		arg.AddedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertQuoteWithNumber = `-- name: InsertQuoteWithNumber :exec
INSERT INTO quotes (number, id, text, game, quoted_at, added_by, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertQuoteWithNumberParams struct {
	Number    int64
	ID        string
	Text      string
	Game      string
	QuotedAt  int64
	AddedBy   sql.NullString
	CreatedAt int64
	UpdatedAt int64
}

func (q *Queries) InsertQuoteWithNumber(ctx context.Context, arg InsertQuoteWithNumberParams) error {
	_, err := q.db.ExecContext(ctx, insertQuoteWithNumber,
		arg.Number,
		arg.ID,
		arg.Text,
		arg.Game,
		arg.QuotedAt,
		arg.AddedBy,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const latestQuote = `-- name: LatestQuote :one
SELECT number, id, text, game, quoted_at, added_by, created_at, updated_at FROM quotes ORDER BY number DESC LIMIT 1
`

func (q *Queries) LatestQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRowContext(ctx, latestQuote)
	var i Quote
	err := row.Scan(
		&i.Number,
		&i.ID,
		&i.Text,
		&i.Game,
		&i.QuotedAt,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuotes = `-- name: ListQuotes :many
SELECT number, id, text, game, quoted_at, added_by, created_at, updated_at FROM quotes ORDER BY number
`

func (q *Queries) ListQuotes(ctx context.Context) ([]Quote, error) {
	rows, err := q.db.QueryContext(ctx, listQuotes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Quote{}
	for rows.Next() {
		var i Quote
		if err := rows.Scan(
			&i.Number,
			&i.ID,
			&i.Text,
			&i.Game,
			&i.QuotedAt,
			&i.AddedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuote = `-- name: RandomQuote :one
SELECT number, id, text, game, quoted_at, added_by, created_at, updated_at FROM quotes ORDER BY random() LIMIT 1
`

func (q *Queries) RandomQuote(ctx context.Context) (Quote, error) {
	row := q.db.QueryRowContext(ctx, randomQuote)
	var i Quote
	err := row.Scan(
		&i.Number,
		&i.ID,
		&i.Text,
		&i.Game,
		&i.QuotedAt,
		&i.AddedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateQuote = `-- name: UpdateQuote :execrows
UPDATE quotes SET text = ?, game = ?, quoted_at = ?, added_by = ?, updated_at = ? WHERE number = ?
`

type UpdateQuoteParams struct {
	Text      string
	Game      string
	QuotedAt  int64
	AddedBy   sql.NullString
	UpdatedAt int64
	Number    int64
}

func (q *Queries) UpdateQuote(ctx context.Context, arg UpdateQuoteParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateQuote,
		arg.Text,
		arg.Game,
		arg.QuotedAt,
		arg.AddedBy,
		arg.UpdatedAt,
		arg.Number,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
