// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secrets.sql

package sqlcgen

import (
	"context"
)

const deleteSecret = `-- name: DeleteSecret :execrows
DELETE FROM secrets WHERE name = ?
`

func (q *Queries) DeleteSecret(ctx context.Context, name string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSecret, name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSecret = `-- name: GetSecret :one
SELECT name, key_id, nonce, ciphertext, updated_at FROM secrets WHERE name = ?
`

func (q *Queries) GetSecret(ctx context.Context, name string) (Secret, error) {
	row := q.db.QueryRowContext(ctx, getSecret, name)
	var i Secret
	err := row.Scan(
		&i.Name,
		&i.KeyID,
		&i.Nonce,
		&i.Ciphertext,
		&i.UpdatedAt,
	)
	return i, err
}

const listSecrets = `-- name: ListSecrets :many
SELECT name, key_id, nonce, ciphertext, updated_at FROM secrets ORDER BY name
`

func (q *Queries) ListSecrets(ctx context.Context) ([]Secret, error) {
	rows, err := q.db.QueryContext(ctx, listSecrets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Secret{}
	for rows.Next() {
		var i Secret
		if err := rows.Scan(
			&i.Name,
			&i.KeyID,
			&i.Nonce,
			&i.Ciphertext,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSecret = `-- name: PutSecret :exec
INSERT INTO secrets (name, key_id, nonce, ciphertext, updated_at) VALUES (?, ?, ?, ?, ?)
ON CONFLICT (name) DO UPDATE SET
    key_id = excluded.key_id,
    nonce = excluded.nonce,
    ciphertext = excluded.ciphertext,
    updated_at = excluded.updated_at
`

type PutSecretParams struct {
	Name       string
	KeyID      string
	Nonce      []byte
	Ciphertext []byte
	UpdatedAt  int64
}

func (q *Queries) PutSecret(ctx context.Context, arg PutSecretParams) error {
	_, err := q.db.ExecContext(ctx, putSecret,
		arg.Name,
		arg.KeyID,
		arg.Nonce,
		arg.Ciphertext,
		arg.UpdatedAt,
	)
	return err
}
