// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT document, updated_at FROM settings WHERE section = ?
`

type GetSettingsRow struct {
	Document  string
	UpdatedAt int64
}

func (q *Queries) GetSettings(ctx context.Context, section string) (GetSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getSettings, section)
	var i GetSettingsRow
	err := row.Scan(&i.Document, &i.UpdatedAt)
	return i, err
}

const listSettings = `-- name: ListSettings :many
SELECT section, document, updated_at FROM settings ORDER BY section
`

func (q *Queries) ListSettings(ctx context.Context) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(&i.Section, &i.Document, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSettings = `-- name: PutSettings :exec
INSERT INTO settings (section, document, updated_at) VALUES (?, ?, ?)
ON CONFLICT (section) DO UPDATE SET document = excluded.document, updated_at = excluded.updated_at
`

type PutSettingsParams struct {
	Section   string
	Document  string
	UpdatedAt int64
}

func (q *Queries) PutSettings(ctx context.Context, arg PutSettingsParams) error {
	_, err := q.db.ExecContext(ctx, putSettings, arg.Section, arg.Document, arg.UpdatedAt)
	return err
}
