// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getIdentity = `-- name: GetIdentity :one
SELECT platform, platform_user_id, user_id, login, display_name, color, avatar_url, roles, followed_at, subscribed_at, sub_tier, account_created_at, data_updated_at, created_at, updated_at FROM user_identities WHERE platform = ? AND platform_user_id = ?
`

type GetIdentityParams struct {
	Platform       string
	PlatformUserID string
}

func (q *Queries) GetIdentity(ctx context.Context, arg GetIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRowContext(ctx, getIdentity, arg.Platform, arg.PlatformUserID)
	var i UserIdentity
	err := row.Scan(
		&i.Platform,
		&i.PlatformUserID,
		&i.UserID,
		&i.Login,
		&i.DisplayName,
		&i.Color,
		&i.AvatarUrl,
		&i.Roles,
		&i.FollowedAt,
		&i.SubscribedAt,
		&i.SubTier,
		&i.AccountCreatedAt,
		&i.DataUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, title, notes, excluded, regular, entrance_command_id, created_at, updated_at FROM users WHERE id = ?
`

// SPDX-License-Identifier: Apache-2.0
func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Notes,
		&i.Excluded,
		&i.Regular,
		&i.EntranceCommandID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT user_id, watch_minutes, messages, commands_run, mentions, streams_watched, first_seen, last_seen, donated_cents, strikes FROM user_stats WHERE user_id = ?
`

func (q *Queries) GetUserStats(ctx context.Context, userID string) (UserStat, error) {
	row := q.db.QueryRowContext(ctx, getUserStats, userID)
	var i UserStat
	err := row.Scan(
		&i.UserID,
		&i.WatchMinutes,
		&i.Messages,
		&i.CommandsRun,
		&i.Mentions,
		&i.StreamsWatched,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DonatedCents,
		&i.Strikes,
	)
	return i, err
}

const insertIdentity = `-- name: InsertIdentity :exec
INSERT INTO user_identities (
    platform, platform_user_id, user_id, login, display_name, color, avatar_url, roles,
    followed_at, subscribed_at, sub_tier, account_created_at, data_updated_at,
    created_at, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertIdentityParams struct {
	Platform         string
	PlatformUserID   string
	UserID           string
	Login            string
	DisplayName      string
	Color            string
	AvatarUrl        string
	Roles            string
	FollowedAt       sql.NullInt64
	SubscribedAt     sql.NullInt64
	SubTier          int64
	AccountCreatedAt sql.NullInt64
	DataUpdatedAt    sql.NullInt64
	CreatedAt        int64
	UpdatedAt        int64
}

func (q *Queries) InsertIdentity(ctx context.Context, arg InsertIdentityParams) error {
	_, err := q.db.ExecContext(ctx, insertIdentity,
		arg.Platform,
		arg.PlatformUserID,
		arg.UserID,
		arg.Login,
		arg.DisplayName,
		arg.Color,
		arg.AvatarUrl,
		arg.Roles,
		arg.FollowedAt,
		arg.SubscribedAt,
		arg.SubTier,
		arg.AccountCreatedAt,
		arg.DataUpdatedAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (id, title, notes, excluded, regular, entrance_command_id, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertUserParams struct {
	ID                string
	Title             string
	Notes             string
	Excluded          int64
	Regular           int64
	EntranceCommandID sql.NullString
	CreatedAt         int64
	UpdatedAt         int64
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser,
		arg.ID,
		arg.Title,
		arg.Notes,
		arg.Excluded,
		arg.Regular,
		arg.EntranceCommandID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const listIdentities = `-- name: ListIdentities :many
SELECT platform, platform_user_id, user_id, login, display_name, color, avatar_url, roles, followed_at, subscribed_at, sub_tier, account_created_at, data_updated_at, created_at, updated_at FROM user_identities WHERE user_id = ? ORDER BY created_at, platform, platform_user_id
`

func (q *Queries) ListIdentities(ctx context.Context, userID string) ([]UserIdentity, error) {
	rows, err := q.db.QueryContext(ctx, listIdentities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentity{}
	for rows.Next() {
		var i UserIdentity
		if err := rows.Scan(
			&i.Platform,
			&i.PlatformUserID,
			&i.UserID,
			&i.Login,
			&i.DisplayName,
			&i.Color,
			&i.AvatarUrl,
			&i.Roles,
			&i.FollowedAt,
			&i.SubscribedAt,
			&i.SubTier,
			&i.AccountCreatedAt,
			&i.DataUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putUserStats = `-- name: PutUserStats :exec
INSERT INTO user_stats (
    user_id, watch_minutes, messages, commands_run, mentions, streams_watched,
    first_seen, last_seen, donated_cents, strikes
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id) DO UPDATE SET
    watch_minutes = excluded.watch_minutes,
    messages = excluded.messages,
    commands_run = excluded.commands_run,
    mentions = excluded.mentions,
    streams_watched = excluded.streams_watched,
    first_seen = excluded.first_seen,
    last_seen = excluded.last_seen,
    donated_cents = excluded.donated_cents,
    strikes = excluded.strikes
`

type PutUserStatsParams struct {
	UserID         string
	WatchMinutes   int64
	Messages       int64
	CommandsRun    int64
	Mentions       int64
	StreamsWatched int64
	FirstSeen      sql.NullInt64
	LastSeen       sql.NullInt64
	DonatedCents   int64
	Strikes        int64
}

func (q *Queries) PutUserStats(ctx context.Context, arg PutUserStatsParams) error {
	_, err := q.db.ExecContext(ctx, putUserStats,
		arg.UserID,
		arg.WatchMinutes,
		arg.Messages,
		arg.CommandsRun,
		arg.Mentions,
		arg.StreamsWatched,
		arg.FirstSeen,
		arg.LastSeen,
		arg.DonatedCents,
		arg.Strikes,
	)
	return err
}

const updateIdentityData = `-- name: UpdateIdentityData :execrows
UPDATE user_identities SET
    followed_at = ?,
    subscribed_at = ?,
    sub_tier = ?,
    account_created_at = ?,
    data_updated_at = ?,
    updated_at = ?
WHERE platform = ? AND platform_user_id = ?
`

type UpdateIdentityDataParams struct {
	FollowedAt       sql.NullInt64
	SubscribedAt     sql.NullInt64
	SubTier          int64
	AccountCreatedAt sql.NullInt64
	DataUpdatedAt    sql.NullInt64
	UpdatedAt        int64
	Platform         string
	PlatformUserID   string
}

func (q *Queries) UpdateIdentityData(ctx context.Context, arg UpdateIdentityDataParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIdentityData,
		arg.FollowedAt,
		arg.SubscribedAt,
		arg.SubTier,
		arg.AccountCreatedAt,
		arg.DataUpdatedAt,
		arg.UpdatedAt,
		arg.Platform,
		arg.PlatformUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateIdentityNames = `-- name: UpdateIdentityNames :exec
UPDATE user_identities SET
    login = ?,
    display_name = ?,
    color = ?,
    avatar_url = ?,
    updated_at = ?
WHERE platform = ? AND platform_user_id = ?
`

type UpdateIdentityNamesParams struct {
	Login          string
	DisplayName    string
	Color          string
	AvatarUrl      string
	UpdatedAt      int64
	Platform       string
	PlatformUserID string
}

func (q *Queries) UpdateIdentityNames(ctx context.Context, arg UpdateIdentityNamesParams) error {
	_, err := q.db.ExecContext(ctx, updateIdentityNames,
		arg.Login,
		arg.DisplayName,
		arg.Color,
		arg.AvatarUrl,
		arg.UpdatedAt,
		arg.Platform,
		arg.PlatformUserID,
	)
	return err
}

const updateIdentityRoles = `-- name: UpdateIdentityRoles :execrows
UPDATE user_identities SET roles = ?, updated_at = ?
WHERE platform = ? AND platform_user_id = ?
`

type UpdateIdentityRolesParams struct {
	Roles          string
	UpdatedAt      int64
	Platform       string
	PlatformUserID string
}

func (q *Queries) UpdateIdentityRoles(ctx context.Context, arg UpdateIdentityRolesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateIdentityRoles,
		arg.Roles,
		arg.UpdatedAt,
		arg.Platform,
		arg.PlatformUserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users SET
    title = ?,
    notes = ?,
    excluded = ?,
    regular = ?,
    entrance_command_id = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Title             string
	Notes             string
	Excluded          int64
	Regular           int64
	EntranceCommandID sql.NullString
	UpdatedAt         int64
	ID                string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Title,
		arg.Notes,
		arg.Excluded,
		arg.Regular,
		arg.EntranceCommandID,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
