// SPDX-License-Identifier: Apache-2.0

// Package store is the SQLite persistence of a profile (ADR-0012,
// Code-ADR-0008): one database file per profile, a writer pool with a single
// connection and a reader pool, embedded goose migrations and typed queries
// generated by sqlc.
//
// Repositories are methods of Store that implement the interfaces their
// consumers define; the generated sqlc types do not leave this package.
package store

import (
	"context"
	"database/sql"
	"embed"
	"errors"
	"fmt"
	"io/fs"
	"log/slog"
	"net/url"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strconv"
	"strings"

	"github.com/pressly/goose/v3"
	"modernc.org/sqlite"
	sqlite3 "modernc.org/sqlite/lib"

	"github.com/ripmav/streamcrew/internal/store/sqlcgen"
)

//go:embed migrations/*.sql
var migrations embed.FS

var (
	// ErrNotFound is returned when a queried row does not exist.
	ErrNotFound = errors.New("not found")
	// ErrConflict is returned when a write violates a uniqueness or foreign
	// key constraint.
	ErrConflict = errors.New("conflict")
	// ErrSchemaTooNew is returned when a database has a newer schema than
	// this version of streamcrew knows.
	ErrSchemaTooNew = errors.New("database schema is newer than this version of streamcrew supports")
)

// busyTimeoutMillis is how long a connection waits for a lock.
const busyTimeoutMillis = 5000

// Option configures Open.
type Option func(*options)

type options struct {
	logger        *slog.Logger
	beforeMigrate func(ctx context.Context, s *Store, from, to int64) error
}

// WithLogger sets the logger; the default discards.
func WithLogger(l *slog.Logger) Option {
	return func(o *options) { o.logger = l }
}

// WithBeforeMigrate registers a function that runs before migrations change
// an existing database, e.g. to back it up. It does not run for a new
// database. An error aborts Open.
func WithBeforeMigrate(f func(ctx context.Context, s *Store, from, to int64) error) Option {
	return func(o *options) { o.beforeMigrate = f }
}

// Store is an open profile database.
type Store struct {
	path    string
	write   *sql.DB
	read    *sql.DB
	logger  *slog.Logger
	version int64
}

// Open opens or creates the database at path and migrates it to the latest
// schema.
func Open(ctx context.Context, path string, opts ...Option) (*Store, error) {
	fsys, err := fs.Sub(migrations, "migrations")
	if err != nil {
		return nil, fmt.Errorf("migrations: %w", err)
	}
	return open(ctx, path, fsys, opts...)
}

// open is Open with the migrations taken from fsys.
func open(ctx context.Context, path string, fsys fs.FS, opts ...Option) (*Store, error) {
	o := options{logger: slog.New(slog.DiscardHandler)}
	for _, opt := range opts {
		opt(&o)
	}
	if err := createFile(path); err != nil {
		return nil, err
	}

	write, err := sql.Open("sqlite", dsn(path, false))
	if err != nil {
		return nil, fmt.Errorf("open database: %w", err)
	}
	write.SetMaxOpenConns(1)
	write.SetMaxIdleConns(1)
	read, err := sql.Open("sqlite", dsn(path, true))
	if err != nil {
		return nil, errors.Join(fmt.Errorf("open database: %w", err), write.Close())
	}
	readers := min(4, runtime.GOMAXPROCS(0))
	read.SetMaxOpenConns(readers)
	read.SetMaxIdleConns(readers)

	s := &Store{path: path, write: write, read: read, logger: o.logger}
	if err := s.migrate(ctx, fsys, o.beforeMigrate); err != nil {
		return nil, errors.Join(err, s.Close())
	}
	return s, nil
}

// Close closes both pools.
func (s *Store) Close() error {
	return errors.Join(s.read.Close(), s.write.Close())
}

// Path returns the database file.
func (s *Store) Path() string {
	return s.path
}

// SchemaVersion returns the schema version of the open database.
func (s *Store) SchemaVersion() int64 {
	return s.version
}

// LatestVersion returns the schema version this version of streamcrew
// migrates to: the highest migration number.
func LatestVersion() int64 {
	versions := knownVersions()
	if len(versions) == 0 {
		return 0
	}
	return versions[len(versions)-1]
}

// Write runs fn in a transaction on the writer pool. The transaction holds
// the write lock from its start (BEGIN IMMEDIATE); it commits if fn returns
// nil and rolls back otherwise.
func (s *Store) Write(ctx context.Context, fn func(q *sqlcgen.Queries) error) error {
	tx, err := s.write.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin transaction: %w", err)
	}
	if err := fn(sqlcgen.New(tx)); err != nil {
		return errors.Join(translate(err), rollback(tx))
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", translate(err))
	}
	return nil
}

// reader returns queries on the reader pool.
func (s *Store) reader() *sqlcgen.Queries {
	return sqlcgen.New(s.read)
}

// VacuumInto writes a consistent, compact copy of the database to dest,
// which must not exist.
func (s *Store) VacuumInto(ctx context.Context, dest string) error {
	if _, err := s.write.ExecContext(ctx, "VACUUM INTO ?", dest); err != nil {
		return fmt.Errorf("vacuum into %s: %w", dest, err)
	}
	return nil
}

func (s *Store) migrate(ctx context.Context, fsys fs.FS, before func(ctx context.Context, s *Store, from, to int64) error) error {
	provider, err := goose.NewProvider(goose.DialectSQLite3, s.write, fsys,
		goose.WithDisableGlobalRegistry(true),
		goose.WithSlog(s.logger),
	)
	if err != nil {
		return fmt.Errorf("migrations: %w", err)
	}
	current, target, err := provider.GetVersions(ctx)
	if err != nil {
		return fmt.Errorf("read schema version: %w", err)
	}
	if current > target {
		return fmt.Errorf("%w: database %d, supported %d", ErrSchemaTooNew, current, target)
	}
	if current < target {
		if current > 0 && before != nil {
			if err := before(ctx, s, current, target); err != nil {
				return fmt.Errorf("before migrating from %d to %d: %w", current, target, err)
			}
		}
		if _, err := provider.Up(ctx); err != nil {
			return fmt.Errorf("migrate from %d to %d: %w", current, target, err)
		}
		s.logger.InfoContext(ctx, "database migrated", "path", s.path, "from", current, "to", target)
	}
	s.version = target
	return nil
}

// dsn builds the file: URI with the validated pragmas of Code-ADR-0008.
func dsn(path string, readOnly bool) string {
	q := url.Values{}
	q.Set("_journal_mode", "WAL")
	q.Set("_foreign_keys", "1")
	q.Set("_busy_timeout", strconv.Itoa(busyTimeoutMillis))
	q.Set("_synchronous", "NORMAL")
	if readOnly {
		q.Set("_query_only", "1")
	} else {
		q.Set("_txlock", "immediate")
	}
	return fileURI(path, q)
}

// fileURI encodes path as a SQLite file: URI, so that characters such as
// '?' or '#' in the path are not read as parameters.
func fileURI(path string, q url.Values) string {
	p := filepath.ToSlash(path)
	if filepath.VolumeName(path) != "" {
		p = "/" + p // file:/C:/… on Windows: an absolute path, as SQLite expects
	}
	u := url.URL{Scheme: "file", Path: p, OmitHost: true, RawQuery: q.Encode()}
	return u.String()
}

// createFile creates the database file and its directory with private
// permissions before SQLite does; SQLite uses the file's permissions for the
// WAL and shared-memory files as well.
func createFile(path string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create database directory: %w", err)
	}
	f, err := os.OpenFile(filepath.Clean(path), os.O_RDWR|os.O_CREATE, 0o600)
	if err != nil {
		return fmt.Errorf("create database file: %w", err)
	}
	return f.Close()
}

func rollback(tx *sql.Tx) error {
	if err := tx.Rollback(); err != nil && !errors.Is(err, sql.ErrTxDone) {
		return fmt.Errorf("rollback: %w", err)
	}
	return nil
}

// translate maps driver errors to the errors of this package (Code-ADR-0003).
func translate(err error) error {
	if errors.Is(err, sql.ErrNoRows) {
		return fmt.Errorf("%w: %w", ErrNotFound, err)
	}
	if e, ok := errors.AsType[*sqlite.Error](err); ok && e.Code()&0xff == sqlite3.SQLITE_CONSTRAINT {
		return fmt.Errorf("%w: %w", ErrConflict, err)
	}
	return err
}

// knownVersions lists the migration numbers in ascending order.
func knownVersions() []int64 {
	entries, err := fs.ReadDir(migrations, "migrations")
	if err != nil {
		return nil
	}
	var versions []int64
	for _, e := range entries {
		num, _, _ := strings.Cut(e.Name(), "_")
		if v, err := strconv.ParseInt(num, 10, 64); err == nil {
			versions = append(versions, v)
		}
	}
	slices.Sort(versions)
	return versions
}
